server:
  servlet:
    context-path: /api
spring:
  application:
    name: @project.name@
    version: @project.version@
    description: @project.description@
  datasource:
    username: worklogminer
    password: worklogminer
    url: jdbc:postgresql://sbddev01:5432/worklogminer
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
  jackson:
    default-property-inclusion: non_null
  swagger-ui:
    path: /swagger-ui.html
keycloak:
  auth-server-url: https://keycloak.3digits.es/auth
  realm: proyecto-base-angular-realm
  resource: pbangular
  credentials:
    secret: Mg2d7VxNBY64LF4wmsW3Hk27NXep0XNU
springdoc:
  swagger-ui:
    path: /swagger-ui.html